server:
  port: 8082
logging:
  level:
    ru.podgoretskaya: DEBUG
spring:
  datasource:
    driver_class_name:
      org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: 'validate'
  liquibase:
      enabled: ${LIQUIBASE_ENABLED}
      change-log: classpath:/db/change-log-master.yaml
      url: ${DB_URL}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
  main:
      allow-bean-definition-overriding: true
#       адрес для AccountingClient, адрес прописан в docker-compose.yml
app:
  accounting-client: ${APP_ACCOUNTING_CLIENT}
